/**
 * Generates the parts of the documentation that restate code, so they cannot drift from it:
 *
 *   docs/errors.md          entirely, from ERROR_CODES and WARNING_CODES (packages/core/src/errors.ts)
 *   docs/plan-format.md     the block between the `generated:outputs` markers, from the outputs each
 *                           built-in op declares (packages/adapters)
 *
 * Run `pnpm docs:gen` after changing either source. scenarios/docs/errors.test.ts fails when a generated
 * file is out of date.
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRegistry } from "../packages/adapters/src/index.js";
import { ERROR_CODES, WARNING_CODES, type ErrorCodeSpec } from "../packages/core/src/errors.js";

export const REPO = fileURLToPath(new URL("..", import.meta.url));

const EXIT_MEANING: Record<number, string> = {
  0: "success, including an apply whose receipt is `partial` (waiting on an external event) or `stale`",
  1: "failure: `plan` found a line in `error` or `blocked`, an apply's receipt is `failed`, or the command stopped on a code with exit 1",
  2: "the command was refused before it ran: the invocation, the plan, a reference, a parameter, the environment or the approval is wrong",
  3: "the scope's lock is held by another run, or this run lost it: wait and re-plan, never force",
};

/** Markdown table cells cannot contain a raw `|` or a newline. */
function cell(s: string | undefined): string {
  return (s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
}

export function renderErrors(): string {
  const codes = Object.entries(ERROR_CODES as Record<string, ErrorCodeSpec>);
  const lines = [
    "<!-- Generated by scripts/gen-docs.ts from packages/core/src/errors.ts. Do not edit: run `pnpm docs:gen`. -->",
    "",
    "# Error codes",
    "",
    "Every failure Sponson reports carries a stable code. In `--json` output and MCP results it is `error.code` of the",
    "envelope (`{ ok: false, command, error: { code, message, hint? } }`) when the command could not run, and",
    "`errorCode` on a plan line or receipt line when one line failed. Branch on the code, never on the message.",
    "",
    "When a command stops on an error, the code decides the exit code (the Exit column). When it runs to the end, line",
    "failures are reported in its output and the exit code is 1. `hint` (the CLI hint column) is the command-line",
    "remedy, appended to the message in text output and present as `error.hint` in JSON. `ok` in the envelope is true",
    "exactly when the exit code is 0.",
    "",
    "## Exit codes",
    "",
    "| Exit | Meaning |",
    "|---|---|",
    ...[0, 1, 2, 3].map((n) => `| ${n} | ${EXIT_MEANING[n]} |`),
    "",
    "## Codes",
    "",
    "| Code | Exit | Meaning | CLI hint |",
    "|---|---|---|---|",
    ...codes.map(([code, spec]) => `| \`${code}\` | ${spec.exit} | ${cell(spec.doc)} | ${cell(spec.cliHint)} |`),
    "",
    "## Warnings",
    "",
    "Warning codes never fail a run and have no exit code.",
    "",
    "| Code | Meaning |",
    "|---|---|",
    ...Object.entries(WARNING_CODES).map(([code, spec]) => `| \`${code}\` | ${cell(spec.doc)} |`),
    "",
    "## Adding a code",
    "",
    "Add it to `ERROR_CODES` in `packages/core/src/errors.ts` with its exit code, a `doc` line and, when the CLI has a",
    "remedy, a `cliHint`; then run `pnpm docs:gen` and commit the regenerated `docs/errors.md`.",
    "",
  ];
  return lines.join("\n");
}

export const OUTPUTS_START = "<!-- generated:outputs:start (scripts/gen-docs.ts; run `pnpm docs:gen`) -->";
export const OUTPUTS_END = "<!-- generated:outputs:end -->";

/** The outputs every built-in op declares, as a table. */
export function renderOutputs(): string {
  const registry = createRegistry();
  const rows: string[] = ["| Op | Output | Available | Sensitive |", "|---|---|---|---|"];
  for (const name of registry.adapterNames()) {
    for (const [opName, op] of Object.entries(registry.adapter(name).ops)) {
      const outputs = Object.entries(op.outputs);
      if (outputs.length === 0) rows.push(`| \`${name}.${opName}\` | (none) | | |`);
      for (const [out, spec] of outputs) {
        const available = spec.available === "external" ? `external (\`${spec.event ?? "external event"}\`)` : "immediate";
        rows.push(`| \`${name}.${opName}\` | \`${out}\` | ${available} | ${spec.sensitive ? "yes" : "no"} |`);
      }
    }
  }
  return rows.join("\n");
}

/** Replace the generated block of a document; throws when the markers are missing. */
export function withBlock(doc: string, start: string, end: string, body: string): string {
  const a = doc.indexOf(start);
  const b = doc.indexOf(end);
  if (a < 0 || b < a) throw new Error(`markers ${start} … ${end} not found`);
  return `${doc.slice(0, a + start.length)}\n${body}\n${doc.slice(b)}`;
}

export interface GeneratedFile {
  /** Repo-relative path. */
  path: string;
  content: string;
}

/** What every generated file should contain, given the current sources. */
export async function generate(): Promise<GeneratedFile[]> {
  const planFormat = "docs/plan-format.md";
  const current = await readFile(join(REPO, planFormat), "utf8");
  return [
    { path: "docs/errors.md", content: renderErrors() },
    { path: planFormat, content: withBlock(current, OUTPUTS_START, OUTPUTS_END, renderOutputs()) },
  ];
}

async function main(): Promise<void> {
  for (const f of await generate()) {
    const path = join(REPO, f.path);
    const before = await readFile(path, "utf8").catch(() => null);
    if (before === f.content) continue;
    await writeFile(path, f.content, "utf8");
    process.stdout.write(`wrote ${f.path}\n`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((e: unknown) => {
    process.stderr.write(`${e instanceof Error ? e.message : String(e)}\n`);
    process.exit(1);
  });
}
