/**
 * Generates the Mintlify documentation site in site/ from the repository's own Markdown, so the site cannot drift
 * from the docs contributors edit:
 *
 *   site/index.mdx, quickstart.mdx, concepts.mdx   README.md, split by its `##` sections
 *   site/guides/github-actions.mdx                 action/README.md
 *   site/guides/agents.mdx                         README.md "For agents" + SKILL.md
 *   site/reference/*.mdx                           docs/plan-format.md, docs/errors.md, examples/ (README and every
 *                                                  plan, embedded), docs/api-verification.md when it exists,
 *                                                  docs/coverage.md, and
 *                                                  the CLI reference from the CLI's own `--help`
 *   site/contributing/**                           CONTRIBUTING.md, ARCHITECTURE.md, docs/adr/, SECURITY.md,
 *                                                  ROADMAP.md, CHANGELOG.md
 *   site/docs.json                                 `navigation` only; every other key is hand-edited in place
 *
 * Each page gets Mintlify frontmatter; the source's own `#` title is dropped (Mintlify renders `title`). Links are
 * rewritten: to a file the site publishes → its site route (`/reference/plan-format#values`), to anything else in
 * the repository → `https://github.com/MishaBear94/Sponson/blob/main/<path>`. Outside code, the characters MDX would
 * parse (`<`, `{`, `}`) are escaped, HTML comments become MDX comments, and generated-block markers are removed.
 *
 * Hand-written pages (the guides in HAND_WRITTEN) carry no generated marker and are never touched. Every generated
 * page starts with a comment naming its source; editing a generated page is pointless, edit the source and run
 * `pnpm site:gen`. scenarios/docs/site.test.ts fails when site/ is out of date or a link or page is missing.
 */
import { existsSync, statSync } from "node:fs";
import { readdir, readFile, unlink, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, posix } from "node:path";
import { pathToFileURL } from "node:url";
import { run } from "../packages/cli/src/main.js";
import { REPO, type GeneratedFile } from "./gen-docs.js";

export const SITE = "site";
export const GITHUB = "https://github.com/MishaBear94/Sponson";
export const GITHUB_BLOB = `${GITHUB}/blob/main/`;
export const GITHUB_TREE = `${GITHUB}/tree/main/`;
/** Every generated page contains this; pages without it are hand-written. */
export const GENERATED_MARK = "Generated by scripts/gen-site.ts";

/** Pages written by hand in site/ (new prose that stitches existing material together). */
export const HAND_WRITTEN = ["guides/adopting", "guides/production-approvals"];

/** README.md's `##` sections, by heading, and the page each goes to. Unlisted sections go to `concepts`. */
const README_SECTIONS: Record<string, string | null> = {
  "Why this exists": "index",
  "What it does": "index",
  "Quick start": "quickstart",
  "For agents": "guides/agents",
  "How it works": "concepts",
  "Verification without a cloud account": "concepts",
  Status: "concepts",
  // The site's navigation replaces these.
  Documentation: null,
  Contributing: null,
  License: null,
};

/** Whole files that are one page each. */
const FILE_PAGES: Record<string, string> = {
  "SKILL.md": "guides/agents",
  "action/README.md": "guides/github-actions",
  "docs/plan-format.md": "reference/plan-format",
  "docs/errors.md": "reference/errors",
  "docs/api-verification.md": "reference/api-verification",
  "docs/coverage.md": "reference/coverage",
  "examples/README.md": "reference/examples",
  examples: "reference/examples",
  "CONTRIBUTING.md": "contributing/contributing",
  "ARCHITECTURE.md": "contributing/architecture",
  "docs/adr/README.md": "contributing/decisions",
  "docs/adr": "contributing/decisions",
  "SECURITY.md": "contributing/security",
  "ROADMAP.md": "contributing/roadmap",
  "CHANGELOG.md": "contributing/changelog",
};

interface PageMeta {
  title: string;
  description: string;
  sidebarTitle?: string;
}

const META: Record<string, PageMeta> = {
  index: { title: "Introduction", description: "Sponson is the plan for everything that ships beside the code." },
  quickstart: { title: "Quickstart", description: "Write a plan, read the diff, apply it: locally and in GitHub Actions." },
  concepts: { title: "Concepts", description: "How a plan runs, where receipts live, and how Sponson is verified without a cloud account." },
  "guides/github-actions": { title: "CI with GitHub Actions", description: "One action for the whole life of a preview environment, and production behind an approval." },
  "guides/agents": { title: "Agents and MCP", description: "Drive Sponson from an agent: the MCP tools, the JSON envelope and the agent skill." },
  "reference/plan-format": { title: "Plan format", description: "Every key of release.plan.yaml, the value forms, environments and the built-in ops." },
  "reference/errors": { title: "Errors", description: "Every error code, its exit code and remedy." },
  "reference/cli": { title: "CLI", description: "The sponson commands and their options." },
  "reference/examples": { title: "Examples", description: "Complete, tested plans to start from." },
  "reference/api-verification": { title: "API verification", description: "How the fake cloud's assumptions are checked against the real provider APIs." },
  "reference/coverage": { title: "Provider coverage", description: "Which per-environment SaaS state Sponson covers today, and the plan to cover the rest." },
  "contributing/contributing": { title: "Contributing", description: "Set up, run the tests, add an adapter, a secret source or a scenario." },
  "contributing/architecture": { title: "Architecture", description: "How plan and apply run through the code: the ledger, scopes, references and redaction." },
  "contributing/decisions": { title: "Decision records", sidebarTitle: "Overview", description: "The design decisions behind Sponson and why they were made." },
  "contributing/security": { title: "Security policy", description: "Supported versions, how to report a vulnerability, and what is in scope." },
  "contributing/roadmap": { title: "Roadmap", description: "What Sponson needs next, cut into pieces one contributor can pick up." },
  "contributing/changelog": { title: "Changelog", description: "Notable changes in every release." },
};

// ---------------------------------------------------------------------------------------------------------------
// Markdown helpers (fence-aware)

const FENCE = /^\s*(`{3,}|~{3,})/;

/** Map every line, telling the callback whether it is inside (or delimits) a fenced code block. */
export function mapLines(md: string, fn: (line: string, fenced: boolean) => string): string {
  let open: string | null = null;
  return md
    .split("\n")
    .map((line) => {
      const m = FENCE.exec(line);
      if (open === null && m) {
        open = m[1]!;
        return fn(line, true);
      }
      if (open !== null) {
        if (m && m[1]![0] === open[0] && m[1]!.length >= open.length && line.trim() === m[1]) open = null;
        return fn(line, true);
      }
      return fn(line, false);
    })
    .join("\n");
}

interface Section {
  heading: string;
  level: number;
  text: string;
}

/** Split at headings of exactly `level` outside fences: the text before the first one, then each section. */
export function splitSections(md: string, level: number): { preamble: string; sections: Section[] } {
  const prefix = `${"#".repeat(level)} `;
  const parts: Array<{ heading: string | null; lines: string[] }> = [{ heading: null, lines: [] }];
  mapLines(md, (line, fenced) => {
    if (!fenced && line.startsWith(prefix)) parts.push({ heading: line.slice(prefix.length).trim(), lines: [] });
    parts[parts.length - 1]!.lines.push(line);
    return line;
  });
  const [pre, ...rest] = parts;
  return { preamble: pre!.lines.join("\n"), sections: rest.map((p) => ({ heading: p.heading!, level, text: p.lines.join("\n") })) };
}

/** Drop YAML frontmatter and the first `# ` heading (with the blank line after it). */
function stripTitle(md: string): string {
  const lines = md.replace(/^---\n[\s\S]*?\n---\n/, "").split("\n");
  let at = -1;
  let i = 0;
  mapLines(lines.join("\n"), (line, fenced) => {
    if (at < 0 && !fenced && line.startsWith("# ")) at = i;
    i++;
    return line;
  });
  if (at >= 0) lines.splice(at, lines[at + 1]?.trim() === "" ? 2 : 1);
  return lines.join("\n");
}

/** The first `# ` heading's text. */
function titleOf(md: string): string {
  let title = "";
  mapLines(md, (line, fenced) => {
    if (!title && !fenced && line.startsWith("# ")) title = line.slice(2).trim();
    return line;
  });
  return title;
}

function shiftHeadings(md: string, by: number): string {
  return mapLines(md, (line, fenced) => (!fenced && /^#{1,5} /.test(line) ? "#".repeat(by) + line : line));
}

/** A heading's text as rendered: link text kept, code and emphasis markers dropped. */
function headingText(heading: string): string {
  return heading.replace(/\[([^\]]*)\]\([^)]*\)/g, "$1").replace(/[`*]/g, "").trim();
}

/** GitHub's anchor for a heading (the same rule scripts/gen-docs.ts uses). */
export function githubSlug(heading: string): string {
  return headingText(heading)
    .toLowerCase()
    .replace(/[^\p{L}\p{M}\p{N}\p{Pc} -]/gu, "")
    .replace(/ /g, "-");
}

/**
 * Mintlify's anchor for a heading, as its renderer and `mint broken-links --check-anchors` compute it (@mintlify/common
 * `slugify` + `cleanHeadingId`): whitespace becomes `-`, characters URI encoding keeps (letters, digits, `-_.!~*'()`)
 * other than letters, digits and `_` become `-` separators, everything else is kept, then `?,;:!'"()[]{}` are dropped.
 */
export function mintSlug(heading: string): string {
  const s = headingText(heading).toLowerCase().replace(/\s+/g, "-");
  const slugged = [...s]
    .map((c) => (/[a-z0-9_]/.test(c) || encodeURIComponent(c) !== c ? c : "-"))
    .join("")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "");
  return slugged.replace(/[?,;:!'"()[\]{}]/g, "");
}

/** The headings of a Markdown text outside fences: GitHub anchor → Mintlify anchor, duplicates numbered by each rule. */
export function headingAnchors(md: string): Map<string, string> {
  const map = new Map<string, string>();
  const gh = new Map<string, number>();
  const mint = new Map<string, number>();
  mapLines(md, (line, fenced) => {
    const m = fenced ? null : /^#{1,6}\s+(.*?)\s*#*\s*$/.exec(line);
    if (m) {
      const g = githubSlug(m[1]!);
      const ng = gh.get(g) ?? 0;
      gh.set(g, ng + 1);
      const t = mintSlug(m[1]!);
      const nt = mint.get(t) ?? 0;
      mint.set(t, nt + 1);
      map.set(ng === 0 ? g : `${g}-${ng}`, nt === 0 ? t : `${t}-${nt + 1}`);
    }
    return line;
  });
  return map;
}

// ---------------------------------------------------------------------------------------------------------------
// Routing and link rewriting

/** Where README.md's anchors live: every `##` and `###` heading → the page its section goes to. */
async function readmeAnchors(): Promise<Map<string, string | null>> {
  const map = new Map<string, string | null>();
  const readme = await readFile(join(REPO, "README.md"), "utf8");
  let page: string | null = "index";
  mapLines(readme, (line, fenced) => {
    const m = fenced ? null : /^(#{2,3}) (.*)$/.exec(line);
    if (m) {
      const heading = m[2]!.trim();
      if (m[1] === "##") page = heading in README_SECTIONS ? README_SECTIONS[heading]! : "concepts";
      if (m[1] === "###" && heading in README_SECTIONS) page = README_SECTIONS[heading]!;
      map.set(githubSlug(heading), page);
    }
    return line;
  });
  return map;
}

export function href(route: string, anchor?: string): string {
  return `${route === "index" ? "/" : `/${route}`}${anchor ? `#${anchor}` : ""}`;
}

class Router {
  constructor(
    private readonly readme: Map<string, string | null>,
    private readonly adrs: Set<string>,
    /** Per published source file: GitHub anchor → Mintlify anchor. */
    private readonly anchors: Map<string, Map<string, string>>,
  ) {}

  /** The site route of a repository path (and anchor), or null when the site does not publish it. */
  route(path: string, anchor: string | undefined): string | null {
    if (path === "README.md") {
      if (!anchor) return "index";
      const page = this.readme.get(anchor);
      return page === undefined ? "index" : page;
    }
    if (FILE_PAGES[path]) return path === "docs/api-verification.md" && !existsSync(join(REPO, path)) ? null : FILE_PAGES[path]!;
    if (this.adrs.has(path)) return `contributing/adr/${posix.basename(path, ".md")}`;
    return null;
  }

  /** Rewrite one link target found in `source` (a repo-relative path). */
  rewrite(link: string, source: string): string {
    let local: string;
    if (link.startsWith(GITHUB_BLOB)) local = link.slice(GITHUB_BLOB.length);
    else if (link.startsWith(GITHUB_TREE)) local = link.slice(GITHUB_TREE.length);
    else if (/^[a-z][a-z0-9+.-]*:/i.test(link)) return link;
    else if (link.startsWith("#")) local = `${source}${link}`;
    else local = posix.normalize(posix.join(posix.dirname(source), link));
    const hash = local.indexOf("#");
    const path = (hash < 0 ? local : local.slice(0, hash)).replace(/\/$/, "") || ".";
    const anchor = hash < 0 ? undefined : local.slice(hash + 1);
    const route = this.route(path, anchor);
    if (route) return href(route, anchor && (this.anchors.get(path)?.get(anchor) ?? anchor));
    const full = join(REPO, path);
    const isDir = existsSync(full) && statSync(full).isDirectory();
    return `${isDir ? GITHUB_TREE : GITHUB_BLOB}${path}${anchor ? `#${anchor}` : ""}`;
  }
}

// ---------------------------------------------------------------------------------------------------------------
// Markdown → MDX

/** Code span, HTML comment: whichever starts first is taken whole. */
const TOKEN = /(`+)([\s\S]*?[^`])\1(?!`)|<!--([\s\S]*?)-->/g;

/** Escape and rewrite prose (no code spans in it). */
function prose(text: string, rewrite: (link: string) => string): string {
  return text.replace(/\]\(([^)\s]+)\)|[<{}]/g, (m, link: string | undefined) => {
    if (link !== undefined) return `](${rewrite(link)})`;
    return m === "<" ? "&lt;" : m === "{" ? "&#123;" : "&#125;";
  });
}

function comment(body: string): string {
  if (/^\s*generated:[a-z-]+:(start|end)\b/.test(body)) return "";
  return `{/* ${body.trim().replace(/\*\//g, "* /")} */}`;
}

/** Turn a run of non-fenced Markdown into MDX. */
function block(text: string, rewrite: (link: string) => string): string {
  let out = "";
  let at = 0;
  for (const m of text.matchAll(TOKEN)) {
    out += prose(text.slice(at, m.index), rewrite);
    out += m[3] !== undefined ? comment(m[3]) : m[0];
    at = m.index + m[0].length;
  }
  return out + prose(text.slice(at), rewrite);
}

/** Markdown (from `source`) → MDX body: fences kept verbatim, everything else escaped and its links rewritten. */
export function toMdx(md: string, source: string, router: Router): string {
  const rewrite = (link: string) => router.rewrite(link, source);
  const chunks: Array<{ fenced: boolean; lines: string[] }> = [];
  mapLines(md, (line, fenced) => {
    const last = chunks[chunks.length - 1];
    if (last && last.fenced === fenced) last.lines.push(line);
    else chunks.push({ fenced, lines: [line] });
    return line;
  });
  return chunks
    .map((c) => (c.fenced ? c.lines.join("\n") : block(c.lines.join("\n"), rewrite)))
    .join("\n")
    .replace(/^[ \t]*\n(?=[ \t]*\n)/gm, "") // a removed marker leaves at most one blank line
    .trim();
}

function page(route: string, meta: PageMeta, sources: string[], body: string): GeneratedFile {
  const front = [
    "---",
    `title: ${JSON.stringify(meta.title)}`,
    ...(meta.sidebarTitle ? [`sidebarTitle: ${JSON.stringify(meta.sidebarTitle)}`] : []),
    `description: ${JSON.stringify(meta.description)}`,
    "---",
    "",
    `{/* ${GENERATED_MARK} from ${sources.join(", ")}. Do not edit: edit the source and run \`pnpm site:gen\`. */}`,
    "",
  ];
  return { path: `${SITE}/${route}.mdx`, content: `${front.join("\n")}\n${body.trim()}\n` };
}

// ---------------------------------------------------------------------------------------------------------------
// Pages

const read = (path: string) => readFile(join(REPO, path), "utf8");

/** Strip terminal colour codes. */
const ANSI = new RegExp(`${String.fromCharCode(27)}\\[[0-9;]*m`, "g");

/** The CLI's `--help` output for `args`, at commander's default width and without colour, whatever the terminal. */
async function help(args: string[]): Promise<string> {
  const streams = [process.stdout, process.stderr];
  const saved = streams.map((s) => Object.getOwnPropertyDescriptor(s, "isTTY"));
  for (const s of streams) Object.defineProperty(s, "isTTY", { value: false, configurable: true, writable: true });
  let out = "";
  try {
    await run([...args, "--help"], { stdout: { write: (s: string) => (out += s) }, stderr: { write: () => true }, env: { NO_COLOR: "1" }, color: false });
  } finally {
    streams.forEach((s, i) => {
      const d = saved[i];
      if (d) Object.defineProperty(s, "isTTY", d);
      else delete (s as { isTTY?: boolean }).isTTY;
    });
  }
  return out.replace(ANSI, "").trimEnd();
}

async function cliPage(): Promise<GeneratedFile> {
  const root = await help([]);
  const commands: string[] = [];
  let inCommands = false;
  for (const line of root.split("\n")) {
    if (/^Commands:/.test(line)) inCommands = true;
    else if (/^\S/.test(line)) inCommands = false;
    else if (inCommands) {
      const name = /^ {2}([a-z][\w-]*)/.exec(line)?.[1];
      if (name && name !== "help") commands.push(name);
    }
  }
  const parts = [
    "This page is the CLI's own `--help` output (`packages/cli/src/main.ts`). Global options go before or after the",
    "command. Every command takes `--json`; what it prints is described in [Agents and MCP](/guides/agents), and every",
    "error code and exit code in [Errors](/reference/errors).",
    "",
    "## sponson",
    "",
    "```text",
    root,
    "```",
  ];
  for (const c of commands) parts.push("", `## sponson ${c}`, "", "```text", await help([c]), "```");
  return page("reference/cli", META["reference/cli"]!, ["packages/cli/src/main.ts (sponson --help)"], parts.join("\n"));
}

async function readmePages(router: Router): Promise<Map<string, string[]>> {
  const readme = await read("README.md");
  const { preamble, sections } = splitSections(stripTitle(readme), 2);
  const bodies = new Map<string, string[]>([["index", [preamble]]]);
  const add = (route: string | null, text: string) => {
    if (route) bodies.set(route, [...(bodies.get(route) ?? []), text]);
  };
  for (const s of sections) {
    const route = s.heading in README_SECTIONS ? README_SECTIONS[s.heading]! : "concepts";
    const sub = splitSections(s.text, 3);
    // The page's own section heading is redundant when the section is the whole page (Quick start).
    const head = route === "quickstart" ? sub.preamble.replace(/^## .*\n/, "") : sub.preamble;
    add(route, head);
    for (const ss of sub.sections) add(ss.heading in README_SECTIONS ? README_SECTIONS[ss.heading]! : route, ss.text);
  }
  const out = new Map<string, string[]>();
  for (const [route, texts] of bodies) out.set(route, [toMdx(texts.join("\n\n"), "README.md", router)]);
  return out;
}

async function examplesPage(router: Router): Promise<GeneratedFile> {
  const md = stripTitle(await read("examples/README.md"));
  const plans = (await readdir(join(REPO, "examples"))).filter((f) => f.endsWith(".plan.yaml")).sort();
  const embed = async (file: string) => `\n\n\`\`\`yaml ${file}\n${(await read(`examples/${file}`)).trimEnd()}\n\`\`\``;
  const { preamble, sections } = splitSections(md, 2);
  const parts = [toMdx(preamble, "examples/README.md", router)];
  const shown = new Set<string>();
  for (const s of sections) {
    let text = toMdx(s.text, "examples/README.md", router);
    if (plans.includes(s.heading)) {
      text += await embed(s.heading);
      shown.add(s.heading);
    }
    parts.push(text);
  }
  const rest = plans.filter((p) => !shown.has(p));
  if (rest.length) {
    parts.push("## More examples");
    for (const p of rest) parts.push(`### ${p}${await embed(p)}`);
  }
  return page("reference/examples", META["reference/examples"]!, ["examples/README.md", "examples/*.plan.yaml"], parts.join("\n\n"));
}

/** The ADR files, sorted. */
async function adrFiles(): Promise<string[]> {
  return (await readdir(join(REPO, "docs/adr"))).filter((f) => /^\d{4}-.*\.md$/.test(f)).sort();
}

async function adrPages(router: Router): Promise<GeneratedFile[]> {
  const out: GeneratedFile[] = [];
  for (const file of await adrFiles()) {
    const source = `docs/adr/${file}`;
    const md = await read(source);
    const num = file.slice(0, 4);
    const name = titleOf(md).replace(/^\d+\.\s*/, "").replace(/`/g, "");
    const status = /^## Status\s*\n+([^\n]+)/m.exec(md)?.[1]?.replace(/`/g, "").replace(/\[([^\]]*)\]\([^)]*\)/g, "$1").trim() ?? "";
    const meta: PageMeta = {
      title: `ADR ${num}: ${name}`,
      sidebarTitle: `${num} ${name}`,
      description: `Architecture decision record ${num}. Status: ${status}`.replace(/\s+$/, ""),
    };
    out.push(page(`contributing/adr/${file.slice(0, -3)}`, meta, [source], toMdx(stripTitle(md), source, router)));
  }
  return out;
}

/** The `navigation` of docs.json. */
async function navigation(): Promise<unknown> {
  const adrs = (await adrFiles()).map((f) => `contributing/adr/${f.slice(0, -3)}`);
  const reference = ["reference/plan-format", "reference/errors", "reference/cli", "reference/examples"];
  if (existsSync(join(REPO, "docs/api-verification.md"))) reference.push("reference/api-verification");
  if (existsSync(join(REPO, "docs/coverage.md"))) reference.push("reference/coverage");
  return {
    tabs: [
      {
        tab: "Documentation",
        groups: [
          { group: "Get started", pages: ["index", "quickstart", "concepts"] },
          { group: "Guides", pages: ["guides/github-actions", "guides/agents", ...HAND_WRITTEN] },
        ],
      },
      { tab: "Reference", groups: [{ group: "Reference", pages: reference }] },
      {
        tab: "Contributing",
        groups: [
          {
            group: "Contributing",
            pages: [
              "contributing/contributing",
              "contributing/architecture",
              { group: "Decisions (ADRs)", pages: ["contributing/decisions", ...adrs] },
              "contributing/security",
              "contributing/roadmap",
              "contributing/changelog",
            ],
          },
        ],
      },
    ],
  };
}

/** What every generated file in site/ should contain, given the current sources. */
export async function generate(): Promise<GeneratedFile[]> {
  const adrs = (await adrFiles()).map((f) => `docs/adr/${f}`);
  const anchors = new Map<string, Map<string, string>>();
  for (const source of ["README.md", ...Object.keys(FILE_PAGES), ...adrs]) {
    if (source.endsWith(".md") && existsSync(join(REPO, source))) anchors.set(source, headingAnchors(await read(source)));
  }
  const router = new Router(await readmeAnchors(), new Set(adrs), anchors);
  const files: GeneratedFile[] = [];

  const readme = await readmePages(router);
  for (const route of ["index", "quickstart", "concepts"]) files.push(page(route, META[route]!, ["README.md"], readme.get(route)!.join("\n\n")));

  const skill = toMdx(shiftHeadings(stripTitle(await read("SKILL.md")), 1), "SKILL.md", router);
  const agents = [
    ...(readme.get("guides/agents") ?? []),
    "## The agent skill",
    `[SKILL.md](${GITHUB_BLOB}SKILL.md) is written for the agent itself: give it to the agent (as a skill, or in its instructions) and it knows when to write a plan line and when to stop for a human. Its full text follows.`,
    skill,
  ];
  files.push(page("guides/agents", META["guides/agents"]!, ["README.md", "SKILL.md"], agents.join("\n\n")));

  const whole: Array<[string, string]> = [
    ["action/README.md", "guides/github-actions"],
    ["docs/plan-format.md", "reference/plan-format"],
    ["docs/errors.md", "reference/errors"],
    ["docs/api-verification.md", "reference/api-verification"],
    ["docs/coverage.md", "reference/coverage"],
    ["CONTRIBUTING.md", "contributing/contributing"],
    ["ARCHITECTURE.md", "contributing/architecture"],
    ["docs/adr/README.md", "contributing/decisions"],
    ["SECURITY.md", "contributing/security"],
    ["ROADMAP.md", "contributing/roadmap"],
    ["CHANGELOG.md", "contributing/changelog"],
  ];
  for (const [source, route] of whole) {
    if (!existsSync(join(REPO, source))) continue;
    files.push(page(route, META[route]!, [source], toMdx(stripTitle(await read(source)), source, router)));
  }
  files.push(await examplesPage(router));
  files.push(await cliPage());
  files.push(...(await adrPages(router)));

  const config = JSON.parse(await read(`${SITE}/docs.json`)) as Record<string, unknown>;
  config.navigation = await navigation();
  files.push({ path: `${SITE}/docs.json`, content: `${JSON.stringify(config, null, 2)}\n` });
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

/** Every .mdx/.md file under site/, repo-relative. */
export async function sitePages(): Promise<string[]> {
  const out: string[] = [];
  const walk = async (dir: string): Promise<void> => {
    for (const e of await readdir(join(REPO, dir), { withFileTypes: true })) {
      const p = `${dir}/${e.name}`;
      if (e.isDirectory()) await walk(p);
      else if (/\.mdx?$/.test(e.name) && p !== `${SITE}/README.md`) out.push(p);
    }
  };
  await walk(SITE);
  return out.sort();
}

/** Generated pages on disk that the sources no longer produce. */
export async function stalePages(files: GeneratedFile[]): Promise<string[]> {
  const expected = new Set(files.map((f) => f.path));
  const stale: string[] = [];
  for (const p of await sitePages()) {
    if (!expected.has(p) && (await read(p)).includes(GENERATED_MARK)) stale.push(p);
  }
  return stale;
}

async function main(): Promise<void> {
  const files = await generate();
  for (const f of files) {
    const path = join(REPO, f.path);
    const before = await readFile(path, "utf8").catch(() => null);
    if (before === f.content) continue;
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, f.content, "utf8");
    process.stdout.write(`wrote ${f.path}\n`);
  }
  for (const p of await stalePages(files)) {
    await unlink(join(REPO, p));
    process.stdout.write(`removed ${p}\n`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((e: unknown) => {
    process.stderr.write(`${e instanceof Error ? e.message : String(e)}\n`);
    process.exit(1);
  });
}
