/**
 * Scaffold a new adapter: `pnpm new:adapter <name> [--dry-run]`.
 *
 * Generates, from templates/adapter/:
 *   packages/adapters/src/<name>.ts        the adapter, one op (`item`) using the @sponson/adapters helpers
 *   packages/adapters/src/<name>.test.ts   its unit tests against the sim
 *   packages/sim/src/routes/<name>.ts      the simulated provider (ProviderSim) with numbered API assumptions
 *   scenarios/adapters/<name>.yaml         an end-to-end scenario through the CLI
 * and registers them: createRegistry() and the exports in packages/adapters/src/index.ts, PROVIDERS in
 * packages/sim/src/state.ts, the routes export in packages/sim/src/index.ts.
 *
 * Idempotent: existing files are left alone and registrations already present are skipped, so re-running after
 * a partial run (or after resolving a conflict by hand) completes the job. Every change is printed.
 */
import { existsSync, realpathSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

export interface ScaffoldResult {
  created: string[];
  skipped: string[];
  edited: Array<{ file: string; change: string }>;
}

const NAME = /^[a-z][a-z0-9]{1,29}$/;
/** Marker the templates carry; a file without it was not generated by this script and is never treated as ours. */
const GENERATED = (name: string) => `pnpm new:adapter ${name}`;

const FILES = (name: string): Array<{ template: string; target: string }> => [
  { template: "adapter.ts.tmpl", target: `packages/adapters/src/${name}.ts` },
  { template: "adapter.test.ts.tmpl", target: `packages/adapters/src/${name}.test.ts` },
  { template: "sim-routes.ts.tmpl", target: `packages/sim/src/routes/${name}.ts` },
  { template: "scenario.yaml.tmpl", target: `scenarios/adapters/${name}.yaml` },
];

export function render(template: string, name: string): string {
  const pascal = name[0]!.toUpperCase() + name.slice(1);
  return template.replace(/__NAME__/g, name.toUpperCase()).replace(/__Name__/g, pascal).replace(/__name__/g, name);
}

/** One registration: `present` says whether it is already there, `apply` returns the edited text (or throws). */
interface Edit {
  file: string;
  change: string;
  present(text: string): boolean;
  apply(text: string): string;
}

/** Insert `line` after the last line matching `anchor` (a whole-line, multiline regex). */
function afterLast(text: string, anchor: RegExp, line: string, what: string, file: string): string {
  const matches = [...text.matchAll(new RegExp(anchor.source, "gm"))];
  const last = matches[matches.length - 1];
  if (!last) throw new Error(`${file}: cannot find where to add ${what} (no line matching ${anchor}); add it by hand: ${line}`);
  const end = last.index + last[0].length;
  return `${text.slice(0, end)}\n${line}${text.slice(end)}`;
}

function edits(name: string): Edit[] {
  const adapter = `${name}Adapter`;
  const sim = `${name}Sim`;
  const ADAPTERS = "packages/adapters/src/index.ts";
  const STATE = "packages/sim/src/state.ts";
  const SIM_INDEX = "packages/sim/src/index.ts";
  const importAdapter = `import { ${adapter} } from "./${name}.js";`;
  const exportAdapter = `export * from "./${name}.js";`;
  const importSim = `import { ${sim} } from "./routes/${name}.js";`;
  const exportSim = `export * from "./routes/${name}.js";`;
  return [
    {
      file: ADAPTERS,
      change: importAdapter,
      present: (t) => t.includes(importAdapter),
      apply: (t) => afterLast(t, /^import \{[^}]*\} from "\.\/[\w-]+\.js";$/, importAdapter, "the import", ADAPTERS),
    },
    {
      file: ADAPTERS,
      change: exportAdapter,
      present: (t) => t.includes(exportAdapter),
      apply: (t) => afterLast(t, /^export \* from "\.\/[\w-]+\.js";$/, exportAdapter, "the export", ADAPTERS),
    },
    {
      file: ADAPTERS,
      change: `createRegistry(): .addAdapter(${adapter})`,
      present: (t) => t.includes(`.addAdapter(${adapter})`),
      apply: (t) => {
        const body = t.match(/export function createRegistry\(\)[^{]*\{[\s\S]*?\n\}/);
        if (!body) throw new Error(`${ADAPTERS}: cannot find createRegistry(); add .addAdapter(${adapter}) to it by hand`);
        const calls = [...body[0].matchAll(/\.addAdapter\(\w+\)/g)];
        const last = calls[calls.length - 1];
        if (!last) throw new Error(`${ADAPTERS}: createRegistry() has no .addAdapter(…) call to follow; add .addAdapter(${adapter}) by hand`);
        const at = body.index! + last.index + last[0].length;
        return `${t.slice(0, at)}.addAdapter(${adapter})${t.slice(at)}`;
      },
    },
    {
      file: STATE,
      change: importSim,
      present: (t) => t.includes(importSim),
      apply: (t) => afterLast(t, /^import \{ \w+Sim \} from "\.\/routes\/[\w-]+\.js";$/, importSim, "the import", STATE),
    },
    {
      file: STATE,
      change: `PROVIDERS: ${name}: ${sim}`,
      present: (t) => new RegExp(`export const PROVIDERS = \\{[^}]*\\b${name}: ${sim}\\b`).test(t),
      apply: (t) => {
        const m = t.match(/export const PROVIDERS = \{([^}]*)\}/);
        if (!m) throw new Error(`${STATE}: cannot find \`export const PROVIDERS = { … }\`; add ${name}: ${sim} to it by hand`);
        const inner = m[1]!;
        const next = inner.includes("\n")
          ? `${inner.replace(/,?\s*$/, ",")}\n  ${name}: ${sim},\n`
          : ` ${inner.trim().replace(/,$/, "")}, ${name}: ${sim} `;
        return t.replace(m[0], `export const PROVIDERS = {${next}}`);
      },
    },
    {
      file: SIM_INDEX,
      change: exportSim,
      present: (t) => t.includes(exportSim),
      apply: (t) => afterLast(t, /^export \* from "\.\/routes\/[\w-]+\.js";$/, exportSim, "the export", SIM_INDEX),
    },
  ];
}

export async function scaffold(name: string, opts: { root: string; templates?: string; dryRun?: boolean }): Promise<ScaffoldResult> {
  if (!NAME.test(name)) throw new Error(`adapter name must match ${NAME} (lowercase letters and digits, starting with a letter), got "${name}"`);
  const templates = opts.templates ?? join(opts.root, "templates/adapter");
  const result: ScaffoldResult = { created: [], skipped: [], edited: [] };

  // Refuse before writing anything if a target exists that this script did not generate (e.g. `clerk`).
  for (const f of FILES(name)) {
    const target = join(opts.root, f.target);
    if (existsSync(target) && !(await readFile(target, "utf8")).includes(GENERATED(name))) {
      throw new Error(`${f.target} already exists and was not generated by \`${GENERATED(name)}\`; pick another name`);
    }
  }

  // Compute every registration edit up front, so an anchor that cannot be found fails before any file changes.
  const texts = new Map<string, string>();
  for (const e of edits(name)) {
    const path = join(opts.root, e.file);
    const text = texts.get(path) ?? (await readFile(path, "utf8"));
    if (e.present(text)) {
      texts.set(path, text);
      continue;
    }
    texts.set(path, e.apply(text));
    result.edited.push({ file: e.file, change: e.change });
  }

  for (const f of FILES(name)) {
    const target = join(opts.root, f.target);
    if (existsSync(target)) {
      result.skipped.push(f.target);
      continue;
    }
    result.created.push(f.target);
    if (opts.dryRun) continue;
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, render(await readFile(join(templates, f.template), "utf8"), name));
  }
  if (!opts.dryRun) {
    for (const [path, text] of texts) {
      if (result.edited.some((e) => join(opts.root, e.file) === path)) await writeFile(path, text);
    }
  }
  return result;
}

function report(name: string, r: ScaffoldResult, root: string, dryRun: boolean): string {
  const verb = dryRun ? "would " : "";
  const lines: string[] = [];
  for (const f of r.created) lines.push(`  ${verb}create  ${f}`);
  for (const f of r.skipped) lines.push(`  exists   ${f} (left alone)`);
  for (const e of r.edited) lines.push(`  ${verb}edit    ${e.file}: ${e.change}`);
  if (r.created.length === 0 && r.edited.length === 0) lines.unshift("  nothing to do: every file and registration is already in place");
  const rel = (p: string) => relative(process.cwd(), join(root, p)) || ".";
  return [
    `${dryRun ? "Dry run: " : ""}scaffolding adapter \`${name}\``,
    ...lines,
    "",
    "Next:",
    `  1. Replace the TODOs in ${rel(`packages/adapters/src/${name}.ts`)} and ${rel(`packages/sim/src/routes/${name}.ts`)}:`,
    "     real op names, params, API paths and response shapes; write the API assumptions (X1…) from the provider's docs.",
    `  2. pnpm vitest run packages/adapters/src/${name}.test.ts`,
    `  3. pnpm vitest run --project scenarios scenarios/runner.test.ts -t ${name}`,
    "  4. pnpm typecheck && pnpm lint && pnpm test, then add a changeset (pnpm changeset).",
    "  See CONTRIBUTING.md, \"Adding an adapter\", for the rules every op must follow.",
  ].join("\n");
}

async function main(argv: string[]): Promise<number> {
  const args = argv.filter((a) => !a.startsWith("--"));
  const dryRun = argv.includes("--dry-run");
  if (args.length !== 1 || argv.includes("--help") || argv.includes("-h")) {
    process.stderr.write("usage: pnpm new:adapter <name> [--dry-run]\n  <name>: lowercase letters and digits, e.g. launchdarkly\n");
    return args.length === 1 ? 0 : 2;
  }
  const name = args[0]!;
  const root = fileURLToPath(new URL("..", import.meta.url));
  try {
    const r = await scaffold(name, { root, dryRun });
    process.stdout.write(report(name, r, root, dryRun) + "\n");
    return 0;
  } catch (e) {
    process.stderr.write(`new:adapter: ${e instanceof Error ? e.message : String(e)}\n`);
    return 1;
  }
}

// Run only as a script, not when imported (by a test). realpath: /tmp and /var are symlinks on macOS.
if (process.argv[1] && existsSync(process.argv[1]) && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
  process.exitCode = await main(process.argv.slice(2));
}
