/**
 * Scaffold a new adapter: `pnpm new:adapter <name> [--dry-run]`.
 *
 * Generates, from templates/adapter/:
 *   packages/adapters/src/<name>.ts        the adapter, one op (`item`) using the @sponson/adapters helpers
 *   packages/adapters/src/<name>.test.ts   its unit tests against the sim
 *   packages/sim/src/routes/<name>.ts      the simulated provider (ProviderSim) with numbered API assumptions
 *   scenarios/adapters/<name>.yaml         an end-to-end scenario through the CLI
 * registers them wherever the repository enumerates adapters: createRegistry() and the exports in
 * packages/adapters/src/index.ts, PROVIDERS in packages/sim/src/state.ts, the routes export in
 * packages/sim/src/index.ts, every name the generated files export in PUBLIC_API
 * (packages/core/src/public-api.test.ts) — read from the rendered files, so whatever the templates export is
 * registered —, and the op's section
 * under "Built-in ops" in docs/plan-format.md (templates/adapter/plan-format-op.md.tmpl); and finally runs
 * `pnpm docs:gen`, because the docs restate the registry, then `pnpm site:gen`, because the documentation site
 * restates docs/plan-format.md.
 *
 * The result passes `pnpm typecheck && pnpm lint && pnpm test` with no manual edit; scenarios/tooling/
 * new-adapter.test.ts runs those checks against a scaffolded copy of the repository.
 *
 * Idempotent: existing files are left alone and registrations already present are skipped, so re-running after
 * a partial run (or after resolving a conflict by hand) completes the job. Every change is printed.
 */
import { spawn } from "node:child_process";
import { existsSync, realpathSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { delimiter, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

export interface ScaffoldResult {
  created: string[];
  skipped: string[];
  edited: Array<{ file: string; change: string }>;
  /** What `pnpm docs:gen` wrote (its output lines); empty when the docs were already up to date or on a dry run. */
  docs: string[];
  /** What `pnpm site:gen` wrote, likewise. */
  site: string[];
}

const NAME = /^[a-z][a-z0-9]{1,29}$/;
/** Marker the templates carry; a file without it was not generated by this script and is never treated as ours. */
const GENERATED = (name: string) => `pnpm new:adapter ${name}`;

/** `pkg`: the package whose entry point re-exports the file, so its exports become that package's public API. */
const FILES = (name: string): Array<{ template: string; target: string; pkg?: string }> => [
  { template: "adapter.ts.tmpl", target: `packages/adapters/src/${name}.ts`, pkg: "@sponson/adapters" },
  { template: "adapter.test.ts.tmpl", target: `packages/adapters/src/${name}.test.ts` },
  { template: "sim-routes.ts.tmpl", target: `packages/sim/src/routes/${name}.ts`, pkg: "@sponson/sim" },
  { template: "scenario.yaml.tmpl", target: `scenarios/adapters/${name}.yaml` },
];

const PUBLIC_API_FILE = "packages/core/src/public-api.test.ts";
const PLAN_FORMAT_FILE = "docs/plan-format.md";
/** The op's documentation, inserted into PLAN_FORMAT_FILE after the last built-in op's section. */
const OP_DOC_TEMPLATE = "plan-format-op.md.tmpl";
/** A built-in op's section heading in PLAN_FORMAT_FILE: ### `adapter.op` */
const OP_HEADING = /^### `[\w-]+\.[\w-]+`$/;

/** Names a TypeScript source exports at top level (the templates use plain `export <kind> <name>` declarations). */
export function exportedNames(source: string): string[] {
  return [...source.matchAll(/^export (?:declare )?(?:abstract )?(?:async )?(?:const|let|function\*?|class|interface|type|enum) (\w+)/gm)].map((m) => m[1]!);
}

/** The block of one package's list in PUBLIC_API: from `"<pkg>": [` to its closing `],`. */
function apiBlock(text: string, pkg: string): { start: number; end: number } | null {
  const open = text.indexOf(`${JSON.stringify(pkg)}: [`);
  if (open < 0) return null;
  const close = text.indexOf("\n  ],", open);
  return close < 0 ? null : { start: open, end: close };
}

export function render(template: string, name: string): string {
  const pascal = name[0]!.toUpperCase() + name.slice(1);
  return template.replace(/__NAME__/g, name.toUpperCase()).replace(/__Name__/g, pascal).replace(/__name__/g, name);
}

/** One registration: `present` says whether it is already there, `apply` returns the edited text (or throws). */
interface Edit {
  file: string;
  change: string;
  present(text: string): boolean;
  apply(text: string): string;
}

/** Insert `line` after the last line matching `anchor` (a whole-line, multiline regex). */
function afterLast(text: string, anchor: RegExp, line: string, what: string, file: string): string {
  const matches = [...text.matchAll(new RegExp(anchor.source, "gm"))];
  const last = matches[matches.length - 1];
  if (!last) throw new Error(`${file}: cannot find where to add ${what} (no line matching ${anchor}); add it by hand: ${line}`);
  const end = last.index + last[0].length;
  return `${text.slice(0, end)}\n${line}${text.slice(end)}`;
}

function edits(name: string, api: Map<string, string[]>, opDoc: string): Edit[] {
  const adapter = `${name}Adapter`;
  const sim = `${name}Sim`;
  const ADAPTERS = "packages/adapters/src/index.ts";
  const STATE = "packages/sim/src/state.ts";
  const SIM_INDEX = "packages/sim/src/index.ts";
  const importAdapter = `import { ${adapter} } from "./${name}.js";`;
  const exportAdapter = `export * from "./${name}.js";`;
  const importSim = `import { ${sim} } from "./routes/${name}.js";`;
  const exportSim = `export * from "./routes/${name}.js";`;
  const missingApi = (t: string, pkg: string, names: string[]) => {
    const b = apiBlock(t, pkg);
    return b ? names.filter((n) => !t.slice(b.start, b.end).includes(JSON.stringify(n))) : names;
  };
  const apiEdits: Edit[] = [...api].map(([pkg, names]) => ({
    file: PUBLIC_API_FILE,
    change: `PUBLIC_API[${JSON.stringify(pkg)}] += ${names.join(", ")}`,
    present: (t) => missingApi(t, pkg, names).length === 0,
    apply: (t) => {
      const b = apiBlock(t, pkg);
      if (!b) throw new Error(`${PUBLIC_API_FILE}: cannot find the ${JSON.stringify(pkg)} list in PUBLIC_API; add ${names.join(", ")} to it by hand`);
      const line = `\n    ${missingApi(t, pkg, names).map((n) => JSON.stringify(n)).join(", ")},`;
      return `${t.slice(0, b.end)}${line}${t.slice(b.end)}`;
    },
  }));
  const opHeading = opDoc.split("\n")[0]!;
  return [
    ...apiEdits,
    {
      file: PLAN_FORMAT_FILE,
      change: `"Built-in ops": ${opHeading} section (from templates/adapter/${OP_DOC_TEMPLATE})`,
      present: (t) => t.split("\n").includes(opHeading),
      apply: (t) => {
        const lines = t.split("\n");
        const last = lines.reduce((at, l, i) => (OP_HEADING.test(l) ? i : at), -1);
        const next = last < 0 ? -1 : lines.findIndex((l, i) => i > last && l.startsWith("#"));
        if (next < 0) throw new Error(`${PLAN_FORMAT_FILE}: cannot find where the built-in ops' sections end (a heading after the last "### \`adapter.op\`" section); add templates/adapter/${OP_DOC_TEMPLATE} by hand`);
        return [...lines.slice(0, next), ...opDoc.replace(/\n+$/, "").split("\n"), "", ...lines.slice(next)].join("\n");
      },
    },
    {
      file: ADAPTERS,
      change: importAdapter,
      present: (t) => t.includes(importAdapter),
      apply: (t) => afterLast(t, /^import \{[^}]*\} from "\.\/[\w-]+\.js";$/, importAdapter, "the import", ADAPTERS),
    },
    {
      file: ADAPTERS,
      change: exportAdapter,
      present: (t) => t.includes(exportAdapter),
      apply: (t) => afterLast(t, /^export \* from "\.\/[\w-]+\.js";$/, exportAdapter, "the export", ADAPTERS),
    },
    {
      file: ADAPTERS,
      change: `createRegistry(): .addAdapter(${adapter})`,
      present: (t) => t.includes(`.addAdapter(${adapter})`),
      apply: (t) => {
        const body = t.match(/export function createRegistry\(\)[^{]*\{[\s\S]*?\n\}/);
        if (!body) throw new Error(`${ADAPTERS}: cannot find createRegistry(); add .addAdapter(${adapter}) to it by hand`);
        const calls = [...body[0].matchAll(/\.addAdapter\(\w+\)/g)];
        const last = calls[calls.length - 1];
        if (!last) throw new Error(`${ADAPTERS}: createRegistry() has no .addAdapter(…) call to follow; add .addAdapter(${adapter}) by hand`);
        const at = body.index! + last.index + last[0].length;
        return `${t.slice(0, at)}.addAdapter(${adapter})${t.slice(at)}`;
      },
    },
    {
      file: STATE,
      change: importSim,
      present: (t) => t.includes(importSim),
      apply: (t) => afterLast(t, /^import \{ \w+Sim \} from "\.\/routes\/[\w-]+\.js";$/, importSim, "the import", STATE),
    },
    {
      file: STATE,
      change: `PROVIDERS: ${name}: ${sim}`,
      present: (t) => new RegExp(`export const PROVIDERS = \\{[^}]*\\b${name}: ${sim}\\b`).test(t),
      apply: (t) => {
        const m = t.match(/export const PROVIDERS = \{([^}]*)\}/);
        if (!m) throw new Error(`${STATE}: cannot find \`export const PROVIDERS = { … }\`; add ${name}: ${sim} to it by hand`);
        const inner = m[1]!;
        const next = inner.includes("\n")
          ? `${inner.replace(/,?\s*$/, ",")}\n  ${name}: ${sim},\n`
          : ` ${inner.trim().replace(/,$/, "")}, ${name}: ${sim} `;
        return t.replace(m[0], `export const PROVIDERS = {${next}}`);
      },
    },
    {
      file: SIM_INDEX,
      change: exportSim,
      present: (t) => t.includes(exportSim),
      apply: (t) => afterLast(t, /^export \* from "\.\/routes\/[\w-]+\.js";$/, exportSim, "the export", SIM_INDEX),
    },
  ];
}

export async function scaffold(name: string, opts: { root: string; templates?: string; dryRun?: boolean }): Promise<ScaffoldResult> {
  if (!NAME.test(name)) throw new Error(`adapter name must match ${NAME} (lowercase letters and digits, starting with a letter), got "${name}"`);
  const templates = opts.templates ?? join(opts.root, "templates/adapter");
  const result: ScaffoldResult = { created: [], skipped: [], edited: [], docs: [], site: [] };

  await refuseForeignFiles(name, opts.root);
  const { rendered, api } = await renderFiles(name, templates);
  const opDoc = render(await readFile(join(templates, OP_DOC_TEMPLATE), "utf8"), name);
  const texts = await planEdits(name, opts.root, api, opDoc, result);

  if (opts.dryRun) {
    for (const f of FILES(name)) (existsSync(join(opts.root, f.target)) ? result.skipped : result.created).push(f.target);
    return result;
  }
  await writeFiles(name, opts.root, rendered, result);
  for (const [path, text] of texts) await writeFile(path, text);
  // The docs restate the registry (the outputs table in docs/plan-format.md); regenerate them from it. Run
  // always, not only after edits, so re-running after a failure here completes the job.
  result.docs = await runScript(opts.root, "docs:gen");
  // The site's plan-format page is generated from docs/plan-format.md, which the scaffold just edited.
  result.site = await runScript(opts.root, "site:gen");
  return result;
}

/** Refuse before writing anything if a target exists that this script did not generate (e.g. `clerk`). */
async function refuseForeignFiles(name: string, root: string): Promise<void> {
  for (const f of FILES(name)) {
    const target = join(root, f.target);
    if (existsSync(target) && !(await readFile(target, "utf8")).includes(GENERATED(name))) {
      throw new Error(`${f.target} already exists and was not generated by \`${GENERATED(name)}\`; pick another name`);
    }
  }
}

/** Every file rendered, and per package the names its new files export (the public-API registration). */
async function renderFiles(name: string, templates: string): Promise<{ rendered: Map<string, string>; api: Map<string, string[]> }> {
  const rendered = new Map<string, string>();
  const api = new Map<string, string[]>();
  for (const f of FILES(name)) {
    const text = render(await readFile(join(templates, f.template), "utf8"), name);
    rendered.set(f.target, text);
    if (f.pkg) api.set(f.pkg, [...(api.get(f.pkg) ?? []), ...exportedNames(text)]);
  }
  return { rendered, api };
}

/**
 * Every registration edit, computed up front so an anchor that cannot be found fails before any file changes.
 * Returns the new text of each file that changes; records the edits in `result`.
 */
async function planEdits(name: string, root: string, api: Map<string, string[]>, opDoc: string, result: ScaffoldResult): Promise<Map<string, string>> {
  const texts = new Map<string, string>();
  const changed = new Set<string>();
  for (const e of edits(name, api, opDoc)) {
    const path = join(root, e.file);
    const text = texts.get(path) ?? (await readFile(path, "utf8"));
    if (e.present(text)) {
      texts.set(path, text);
      continue;
    }
    texts.set(path, e.apply(text));
    changed.add(path);
    result.edited.push({ file: e.file, change: e.change });
  }
  return new Map([...texts].filter(([path]) => changed.has(path)));
}

/** Create the rendered files. Create-only (`wx`): an existing file is kept and reported, never overwritten. */
async function writeFiles(name: string, root: string, rendered: Map<string, string>, result: ScaffoldResult): Promise<void> {
  for (const f of FILES(name)) {
    const target = join(root, f.target);
    await mkdir(dirname(target), { recursive: true });
    const written = await writeFile(target, rendered.get(f.target)!, { flag: "wx" }).then(
      () => true,
      (e: NodeJS.ErrnoException) => {
        if (e.code === "EEXIST") return false;
        throw e;
      },
    );
    (written ? result.created : result.skipped).push(f.target);
  }
}

/**
 * Run one of the repository's generator scripts (`docs:gen`, `site:gen`) as `pnpm <name>` would (package.json is the
 * contract, not the generator's internals), in a fresh process so it sees the registrations just written. Returns
 * its output lines.
 */
async function runScript(root: string, name: string): Promise<string[]> {
  const scripts = (JSON.parse(await readFile(join(root, "package.json"), "utf8")) as { scripts?: Record<string, string> }).scripts ?? {};
  const command = scripts[name];
  if (!command) throw new Error(`package.json has no \`${name}\` script; cannot regenerate the docs`);
  const env = { ...process.env, PATH: `${join(root, "node_modules/.bin")}${delimiter}${process.env.PATH ?? ""}` };
  const { code, out } = await new Promise<{ code: number | null; out: string }>((resolve, reject) => {
    const child = spawn(command, { cwd: root, env, shell: true, stdio: ["ignore", "pipe", "pipe"] });
    let out = "";
    child.stdout.on("data", (c: Buffer) => (out += c.toString()));
    child.stderr.on("data", (c: Buffer) => (out += c.toString()));
    child.on("error", reject);
    child.on("close", (c) => resolve({ code: c, out }));
  });
  if (code !== 0) throw new Error(`the adapter is scaffolded, but \`pnpm ${name}\` failed (exit ${code}):\n${out.trim()}\nFix it and run \`pnpm ${name}\`.`);
  return out.split("\n").map((l) => l.trim()).filter(Boolean);
}

function report(name: string, r: ScaffoldResult, root: string, dryRun: boolean): string {
  const verb = dryRun ? "would " : "";
  const lines: string[] = [];
  for (const f of r.created) lines.push(`  ${verb}create  ${f}`);
  for (const f of r.skipped) lines.push(`  exists   ${f} (left alone)`);
  for (const e of r.edited) lines.push(`  ${verb}edit    ${e.file}: ${e.change}`);
  if (dryRun) lines.push("  would run     pnpm docs:gen", "  would run     pnpm site:gen");
  else {
    lines.push(`  ran     pnpm docs:gen: ${r.docs.length ? r.docs.join("; ") : "generated docs already up to date"}`);
    lines.push(`  ran     pnpm site:gen: ${r.site.length ? r.site.join("; ") : "documentation site already up to date"}`);
  }
  if (r.created.length === 0 && r.edited.length === 0 && r.docs.length === 0 && r.site.length === 0) lines.unshift("  nothing to do: every file and registration is already in place");
  const rel = (p: string) => relative(process.cwd(), join(root, p)) || ".";
  return [
    `${dryRun ? "Dry run: " : ""}scaffolding adapter \`${name}\``,
    ...lines,
    "",
    "Next (everything above already passes pnpm typecheck, pnpm lint and pnpm test):",
    `  1. Replace the TODOs in ${rel(`packages/adapters/src/${name}.ts`)} and ${rel(`packages/sim/src/routes/${name}.ts`)}:`,
    "     real op names, params, API paths and response shapes; write the API assumptions (X1…) from the provider's docs.",
    "     Every export needs a doc comment; a renamed or added export goes into PUBLIC_API in",
    `     ${rel(PUBLIC_API_FILE)} (re-running this command adds the template's names only).`,
    `  2. pnpm vitest run packages/adapters/src/${name}.test.ts`,
    `  3. pnpm vitest run --project scenarios scenarios/runner.test.ts -t ${name}`,
    `  4. Docs and schema: rewrite the op's section under "Built-in ops" in ${rel(PLAN_FORMAT_FILE)} and the`,
    "     adapter's `about` (credential and base-URL variables) for the real API; run pnpm docs:gen and pnpm site:gen again",
    `     after changing ops or outputs; and in ${rel("schema/release.plan.schema.json")} add the \`providers.${name}\``,
    "     block and the op's params definition, unless docs:gen generates them (scenarios/docs/ checks both).",
    "  5. pnpm typecheck && pnpm lint && pnpm test, then add a changeset (pnpm changeset).",
    "  See CONTRIBUTING.md, \"Adding an adapter\", for the rules every op must follow.",
  ].join("\n");
}

const USAGE = [
  "usage: pnpm new:adapter <name> [--dry-run]",
  "",
  "Scaffold an adapter, its unit tests, its sim routes and a scenario, register them, and regenerate the docs.",
  "",
  "  <name>      lowercase letters and digits, starting with a letter, e.g. launchdarkly",
  "  --dry-run   print what would be created and edited, change nothing",
  "  -h, --help  show this help",
  "",
  "See CONTRIBUTING.md, \"Adding an adapter\".",
  "",
].join("\n");

async function main(argv: string[]): Promise<number> {
  if (argv.includes("--help") || argv.includes("-h")) {
    process.stdout.write(USAGE);
    return 0;
  }
  const options = argv.filter((a) => a.startsWith("-"));
  const args = argv.filter((a) => !a.startsWith("-"));
  const unknown = options.filter((o) => o !== "--dry-run");
  if (args.length !== 1 || unknown.length > 0) {
    process.stderr.write(`${unknown.length ? `new:adapter: unknown option ${unknown.join(", ")}\n` : ""}${USAGE}`);
    return 2;
  }
  const dryRun = options.includes("--dry-run");
  const name = args[0]!;
  const root = fileURLToPath(new URL("..", import.meta.url));
  try {
    const r = await scaffold(name, { root, dryRun });
    process.stdout.write(report(name, r, root, dryRun) + "\n");
    return 0;
  } catch (e) {
    process.stderr.write(`new:adapter: ${e instanceof Error ? e.message : String(e)}\n`);
    return 1;
  }
}

// Run only as a script, not when imported (by a test). realpath: /tmp and /var are symlinks on macOS.
if (process.argv[1] && existsSync(process.argv[1]) && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
  process.exitCode = await main(process.argv.slice(2));
}
