/** Unit tests for the Supabase adapter against the in-process sim. Generated by `pnpm new:adapter supabase`. */
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { resolveParams } from "@sponson/core";
import { supabaseAdapter } from "./supabase.js";
import { harness, writeIndex, type Harness } from "./testing.js";

const op = supabaseAdapter.ops.item!;
const provider = { project: "demo" };
const params = { name: "sponson-preview-pr-42", value: "v1" };
const KEY = `item:${params.name}`;

describe("supabase item", () => {
  let h: Harness;
  beforeEach(async () => {
    h = await harness();
  });
  afterEach(() => h.close());

  it("create, unchanged, update, destroy", async () => {
    const actx = h.actx("supabase", provider);
    expect(await op.read(actx, params)).toBeNull();
    expect(op.diff(null, params)).toEqual([{ key: KEY, kind: "create", label: `Supabase item ${params.name}`, before: { state: "absent" }, after: { state: "literal", value: "v1" } }]);

    const r = await op.apply(actx, params, null);
    expect(r.created).toEqual([KEY]);
    // The intent was recorded before the create was sent.
    expect(h.intents).toEqual([{ keys: [KEY], writesBefore: 0 }]);
    expect(writeIndex(h, "POST", /^\/supabase\/projects\/demo\/items$/)).toBe(0);

    // apply; apply: the second performs zero writes.
    const live = await op.read(actx, params);
    expect(live?.outputs).toEqual({ id: r.outputs.id, value: "v1" });
    expect(op.diff(live, params)).toEqual([{ key: KEY, kind: "unchanged", label: `Supabase item ${params.name}` }]);
    const writes = (await h.writes()).length;
    expect((await op.apply(actx, params, live)).created).toEqual([]);
    expect((await h.writes()).length).toBe(writes);

    const changed = { ...params, value: "v2" };
    expect(op.diff(live, changed)[0]).toMatchObject({ kind: "update", before: { state: "literal", value: "v1" }, after: { state: "literal", value: "v2" } });
    const u = await op.apply(actx, changed, live);
    expect(u.created).toEqual([]);
    expect(u.outputs).toEqual({ id: r.outputs.id, value: "v2" });

    await op.destroy(actx, u.resources);
    expect(await op.read(actx, params)).toBeNull();
    await op.destroy(actx, u.resources); // already gone is success
  });

  it("a name that already exists (409) is re-read and returned as existing, not created", async () => {
    const actx = h.actx("supabase", provider);
    // Someone (or our own earlier, lost request) creates it between our read and our write.
    await fetch(`${h.sim.url}/supabase/projects/demo/items`, { method: "POST", body: JSON.stringify(params), headers: { authorization: "Bearer other", "content-type": "application/json" } });
    const r = await op.apply(actx, params, null);
    expect(r.created).toEqual([]);
    expect(h.intents.map((i) => i.keys)).toEqual([[KEY]]);
    expect(r.resources.map((x) => x.key)).toEqual([KEY]);
    expect(h.sim.state.supabase.projects.demo!.items).toHaveLength(1);
  });

  it("{ keep: true } is unchanged when the item exists and leaves its value alone", async () => {
    await h.close();
    h = await harness({ supabase: { projects: { demo: [{ name: params.name, value: "human" }] } } });
    const actx = h.actx("supabase", provider);
    const kept = resolveParams({ name: params.name, value: { keep: true } }, new Map()).params;
    const live = await op.read(actx, kept);
    expect(op.diff(live, kept)[0]!.kind).toBe("unchanged");
    const writes = (await h.writes()).length;
    await op.apply(actx, kept, live);
    expect((await h.writes()).length).toBe(writes);
    expect(() => op.diff(null, kept)).toThrow(/keep/);
  });

  it("reads every page of a paginated list", async () => {
    await h.close();
    const seeded = ["a", "b", "c", params.name, "e"].map((name) => ({ name, value: name }));
    h = await harness({ supabase: { projects: { demo: seeded } }, chaos: { page_size: 2 } });
    const actx = h.actx("supabase", provider);
    expect((await op.read(actx, params))?.resources.map((r) => r.key)).toEqual([KEY]);
    expect(await op.listScope!(actx, params)).toHaveLength(5);
  });

  it("a GET that answers 502 once is retried", async () => {
    await h.chaos({ fail_on: "GET /supabase/projects/demo/items", fail_next: 1, status: 502 });
    expect(await op.read(h.actx("supabase", provider), params)).toBeNull();
    expect(h.sim.state.chaos.fail_next).toBe(0);
  });

  it("names what is missing: the token, the project, a param", async () => {
    await expect(op.read({ ...h.actx("supabase", provider), env: {} }, params)).rejects.toMatchObject({ code: "PROVIDER_AUTH" });
    await expect(op.read(h.actx("supabase", {}), params)).rejects.toMatchObject({ code: "PLAN_INVALID" });
    await expect(op.read(h.actx("supabase", provider), {})).rejects.toMatchObject({ code: "PARAM_INVALID" });
  });
});

describe("supabase item adopt", () => {
  it("one line per item, value kept, never copied", () => {
    const ctx = { env: "preview", git: { branch: "feat/x", sha: "abc", short_sha: "abc" }, pr: { number: null }, scope: "branch-feat-x" };
    expect(op.adopt!([{ key: KEY }], ctx)).toEqual([{ id: "item", params: { name: params.name, value: { keep: true } }, keys: [KEY] }]);
  });
});
